eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
#以/api-a/ 开头的请求都转发给service-ribbon服务；
#以/api-b/开头的请求都转发给service-feign服务；
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000